### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by jahorne** [sdbrody/crosserville-toolkit#1]
Nicely done.  A couple of suggestions.

1. You might want to make use of map((element, index) => { /* Perform operation */ })

For example: flippedGrid = puzzle[0].map((_, iCol) => puzzle.map(iRow => iRow[iCol]));

2. jQuery is out of fashion but could be very helpful for you in making your code much smaller and more readable.

For example, instead of iterating through activePanes,, you can simply:

$(".activePane", "#activeTab").removeClass("activePane");

Just some ideas based on a VERY cursory glance at your code. Thanks for sharing it.

**Comment by sdbrody** [comment]
Thanks Jim!
My Javascript is pretty rusty, and was never great in the first place, so suggestion that make it better and more readable are great.
I find map() a little tricky to comprehend (as a reader) at times, but I definitely think that I can make the transformation code less confusing, with or without map(). 
I'm hesitant to pull in jQuery unless it gives a substantial benefit, but I think I can avoid the iterations with pure Javascript, as well.
I'll give it a try when I find the time, and mark this resolved.

**Comment by sdbrody** [comment]
Cleaned up the code and made it more readable in the latest version. Still using a few iterations, but I think it's much better.
Thanks for the suggestions!
